Skip Python 3.9 build on Mac arm64
Testing the Python wheels fails during building the wheel with error
message:

    fatal error: 'H5public.h' file not
    [...]

    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.

I am currently not sure what causes this. Building the wheels appears to
be fine.